version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore: []
  - package-ecosystem: gitsubmodule
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - automated
      - dependencies
      - submodules
